# To be placed in ~/ or ~/.config/alacritty/
[font]
size = 11.0

[keyboard]
bindings = [
    {key="+", mods="Control | Shift", action="IncreaseFontSize"},
    {key="-", mods="Control", action="DecreaseFontSize"}
]
